### ISSUE TITLE
How does Shana Morton really look like?

### ISSUE THREAD

**Issue by heubeck** [answerdev/answer.dev#89]
Hey everyone,

thank you for the really cool and shiny Answer project!
Beside the code base, also the website, documentation and team is really awesome.

But it confuses me, that Shana seems to look different in mobile view ;)

![image](https://github.com/answerdev/answer.dev/assets/40993644/645f09bd-4044-487e-8a1a-3ced1b8b8e93)

Cheers!

**Comment by fenbox** [comment]
Thank you for your correction. It has been fixed.
